export const T = {
  fr: {
    'nav-home':'Accueil','nav-qr':'QR Code','nav-dossier':'Dossier','nav-doctors':'Médecins','nav-profile':'Profil',
    greet:'Bonjour 👋', summaryLabel:'Mon résumé',
    treatments:'Traitements', doctors:'Médecins', metrics:'Métriques',
    quickActions:'Actions rapides',
    actQr:'Mon QR Code urgence', actQrSub:'Accès immédiat pour les médecins',
    actDossier:'Dossier médical', actDossierSub:'Médicaments, antécédents, vaccins',
    actDoctors:'Gérer les accès médecins', actDoctorsSub:'Donner ou révoquer l\'accès',
    actSuivi:'Suivi santé & famille', actSuiviSub:'Courbes, métriques, proches',
    qrTitle:'Mon VitaPass', emergencyTxt:'MODE URGENCE ACTIVÉ', qrTag:'🔐 ID Médical Sécurisé',
    scansLabel:'Historique des scans',
    scan1:'Dr. Meziane — CHU Oran', scan1t:'Hier 14:32',
    scan2:'Urgences — Clinique El Hayat', scan2t:'12 avr.',
    scan3:'Dr. Boudiaf — Cabinet Alger', scan3t:'3 avr.',
    nfcTitle:'Compatible NFC', nfcSub:'Bracelet médical connecté disponible',
    shareBtn:'Partager', printBtn:'Imprimer', nfcBtn:'NFC', securityBtn:'Sécurité',
    dossierTitle:'Dossier Médical',
    tabMeds:'Traitements', tabAnt:'Antécédents', tabVacc:'Vaccins', tabDocs:'Documents',
    enCours:'En cours', termines:'Terminés', allergiesLabel:'Allergies',
    chroniques:'Maladies chroniques', vaccinsLabel:'Calendrier vaccinal', docsLabel:'Documents médicaux',
    addMed:'Ajouter un médicament', addAllergy:'Ajouter une allergie',
    addAnt:'Ajouter un antécédent', addVacc:'Ajouter un vaccin', addDoc:'Importer un document',
    doctorsTitle:'Médecins & Accès', addDoctor:'Ajouter un médecin',
    authorized:'Médecins autorisés', rdvLabel:'Prochains rendez-vous', addRdv:'Ajouter un rendez-vous',
    urgencesLabel:'Urgences Algérie', pompiers:'Pompiers',
    findHosp:'📍 Trouver un hôpital près de moi', wilayasCovered:'58 wilayas couvertes',
    suiviTitle:'Suivi & Famille', metricsLabel:'Mes métriques',
    glycTitle:'Glycémie', glycSub:'Appuyer pour saisir',
    bpTitle:'Tension artérielle', bpSub:'Appuyer pour saisir',
    weightTitle:'Poids', weightSub:'Appuyer pour saisir',
    familyLabel:'Ma famille', addFam:'Ajouter', remindersLabel:'Rappels médicaments',
    personalInfo:'Informations personnelles',
    fnameLabel:'Prénom', lnameLabel:'Nom', dobLabel:'Date de naissance',
    genderLabel:'Sexe', wilayaLabel:'Wilaya', bloodLabel:'Groupe sanguin',
    cnasLabel:'N° CNAS', emergencyLabel:'Contact urgence',
    editProfile:'Modifier mon profil', settingsLabel:'Paramètres',
    sSecurity:'Sécurité & Biométrie', sNotifs:'Notifications & rappels', sLang:'Langue · Français',
    sJournal:'Journal des accès', sBackup:'Sauvegarde & export', sAbout:'À propos · VitaPass v1.0',
    logout:'Se déconnecter', langBtn:'عربي',
    saved:'Enregistré ✓', deleted:'Supprimé ✓', copied:'Lien copié ✓',
    accessFull:'Accès complet', accessLimited:'Accès partiel', revoke:'Révoquer',
    actif:'Actif', chronic:'Chronique', noBorn:'Né le', ans:'ans', annuler:'Annuler',
    noMeds:'Aucun médicament', noAnt:'Aucun antécédent', noDocs:'Aucun document',
    noDoctors:'Aucun médecin', noRdv:'Aucun rendez-vous', noReminders:'Aucun rappel',
    alertPrefix:'Rappel :', alertSuffix:'dans 3 jours',
  },
  ar: {
    'nav-home':'الرئيسية','nav-qr':'رمز QR','nav-dossier':'الملف','nav-doctors':'الأطباء','nav-profile':'الملف الشخصي',
    greet:'مرحباً 👋', summaryLabel:'ملخصي',
    treatments:'علاجات', doctors:'أطباء', metrics:'مقاييس',
    quickActions:'إجراءات سريعة',
    actQr:'رمز QR للطوارئ', actQrSub:'وصول فوري للأطباء',
    actDossier:'الملف الطبي الكامل', actDossierSub:'الأدوية، السوابق، اللقاحات',
    actDoctors:'إدارة صلاحيات الأطباء', actDoctorsSub:'منح أو إلغاء الصلاحية',
    actSuivi:'المتابعة والعائلة', actSuiviSub:'المنحنيات، المقاييس، المقربون',
    qrTitle:'بطاقتي VitaPass', emergencyTxt:'وضع الطوارئ مفعَّل 🚨', qrTag:'🔐 الهوية الطبية المؤمَّنة',
    scansLabel:'سجل المسح',
    scan1:'د. مزيان — جامعي وهران', scan1t:'أمس 14:32',
    scan2:'طوارئ — عيادة الحياة', scan2t:'12 أبريل',
    scan3:'د. بوضياف — عيادة الجزائر', scan3t:'3 أبريل',
    nfcTitle:'متوافق مع NFC', nfcSub:'سوار طبي متصل متاح',
    shareBtn:'مشاركة', printBtn:'طباعة', nfcBtn:'NFC', securityBtn:'الأمان',
    dossierTitle:'الملف الطبي',
    tabMeds:'العلاجات', tabAnt:'السوابق', tabVacc:'اللقاحات', tabDocs:'الوثائق',
    enCours:'جارية', termines:'منتهية', allergiesLabel:'الحساسيات',
    chroniques:'الأمراض المزمنة', vaccinsLabel:'جدول التلقيح', docsLabel:'الوثائق الطبية',
    addMed:'+ إضافة دواء', addAllergy:'+ إضافة حساسية',
    addAnt:'+ إضافة سابقة', addVacc:'+ إضافة لقاح', addDoc:'+ استيراد وثيقة',
    doctorsTitle:'الأطباء والصلاحيات', addDoctor:'إضافة طبيب',
    authorized:'الأطباء المخوَّلون', rdvLabel:'المواعيد القادمة', addRdv:'إضافة موعد',
    urgencesLabel:'طوارئ الجزائر', pompiers:'مطافئ',
    findHosp:'📍 البحث عن مستشفى قريب', wilayasCovered:'تغطية 58 ولاية',
    suiviTitle:'المتابعة والعائلة', metricsLabel:'مقاييسي',
    glycTitle:'السكر في الدم', glycSub:'اضغط للإدخال',
    bpTitle:'ضغط الدم', bpSub:'اضغط للإدخال',
    weightTitle:'الوزن', weightSub:'اضغط للإدخال',
    familyLabel:'عائلتي', addFam:'إضافة', remindersLabel:'تذكيرات الأدوية',
    personalInfo:'المعلومات الشخصية',
    fnameLabel:'الاسم', lnameLabel:'اللقب', dobLabel:'تاريخ الميلاد',
    genderLabel:'الجنس', wilayaLabel:'الولاية', bloodLabel:'فصيلة الدم',
    cnasLabel:'رقم CNAS', emergencyLabel:'جهة اتصال الطوارئ',
    editProfile:'تعديل ملفي الشخصي', settingsLabel:'الإعدادات',
    sSecurity:'الأمان والبيومتري', sNotifs:'الإشعارات والتذكيرات', sLang:'اللغة · العربية',
    sJournal:'سجل الوصول', sBackup:'النسخ الاحتياطي', sAbout:'حول · VitaPass الإصدار 1.0',
    logout:'تسجيل الخروج', langBtn:'FR',
    saved:'تم الحفظ ✓', deleted:'تم الحذف ✓', copied:'تم النسخ ✓',
    accessFull:'صلاحية كاملة', accessLimited:'صلاحية جزئية', revoke:'إلغاء',
    actif:'نشط', chronic:'مزمن', noBorn:'مولود', ans:'سنة', annuler:'إلغاء',
    noMeds:'لا توجد أدوية', noAnt:'لا توجد سوابق', noDocs:'لا توجد وثائق',
    noDoctors:'لا يوجد أطباء', noRdv:'لا توجد مواعيد', noReminders:'لا توجد تذكيرات',
    alertPrefix:'تذكير:', alertSuffix:'خلال 3 أيام',
  }
};